%% Parameter initialisation - point-mass model of an aircraft (level flight)
g = 9.81;                       % acceleration due to gravity (m/s^2)
M = 2994;                       % aircraft mass (kg)
S = 30.19;                      % characteristic surface (m^2)
altitude = 3000;                % level flight altitude (m) 
rho = get_rho(altitude);        % air desnity at given altitude (kg/m^3)
initTAS = 66.5;                 % initial true air speed (m/s)
Cl = [0.2; 4.8];                % lift coefficients (-, 1/rad)
Cd = [0.0357; 0.0763; 1.4515];  % drag coefficients (-, 1/rad, 1/rad^2)